# needssslcertforbuild
# SPDX-License-Identifier: LGPL-2.1-or-later

[Content]
BuildPackages=
        authselect
        bash
        basesystem
        binutils
        btrfs-progs
        ca-certificates
        chrony
        container-selinux
        containers-common
        coreutils
        cryptsetup
        dbus-broker
        dosfstools
        e2fsprogs
        fedora-release
        findutils
        gnupg2
        gzip
        hardened_malloc
        iproute
        ipe-policy-containerhost
        kernel-core
        kernel-modules-core
        kmod
        less
        libcurl-minimal
        libfdisk
        libfido2
        libseccomp
        nftables
        no_rlimit_as
        openssh-server
        openssl
        pam
        podman
        policycoreutils
        polkit
        procps-ng
        runsc
        sbsigntools
        sed
        selinux-policy-targeted
        shadow-utils
        systemd
        systemd-boot
        systemd-container
        systemd-networkd
        systemd-networkd-defaults
        systemd-oomd-defaults
        systemd-pam
        systemd-resolved
        tpm2-tools
        tpm2-tss
        udev
        util-linux
        util-linux-core
        veritysetup
        xfsprogs
        zstd
