# SPDX-License-Identifier: LGPL-2.1-or-later

# OBS workers receive all RPMs through /.build.binaries. Local builds instead
# use the same signed repositories that back the production image build.
[Match]
PathExists=!/.build.binaries

[Build]
SandboxTrees=%D/mkosi.profiles/obs-repos/systemd.gpg:/usr/share/pki/rpm-gpg/systemd.gpg
             %D/mkosi.profiles/obs-repos/systemd.repo:/etc/yum.repos.d/systemd.repo
             %D/mkosi.resources/particleos-obs-pubkey.gpg:/usr/share/pki/rpm-gpg/particleos-obs-pubkey.gpg
             %D/mkosi.resources/particleos-base-obs.repo:/etc/yum.repos.d/particleos-base-obs.repo
