# SPDX-License-Identifier: LGPL-2.1-or-later

[containers]
cgroupns = "private"
host_containers_internal_ip = "none"
http_proxy = false
ipcns = "private"
keyring = false
label = false
log_driver = "journald"
netns = "private"
pidns = "private"
privileged = false
read_only = true
userns = "host"
utsns = "private"

[engine]
cgroup_manager = "systemd"
events_logger = "journald"
pull_policy = "always"
runtime = "runsc"
runtime_supports_json = ["runsc"]

[engine.runtimes]
runsc = ["/usr/libexec/gvisor/runsc"]

[engine.runtimes_flags]
runsc = ["platform=systrap"]

[network]
firewall_driver = "nftables"
network_backend = "netavark"
