IPQoS cs2 cs0

HostKey /etc/ssh/ssh_host_ed25519_key
HostKeyAlgorithms ssh-ed25519
KexAlgorithms mlkem768x25519-sha256
PubkeyAcceptedAlgorithms ssh-ed25519
Ciphers aes256-gcm@openssh.com
MACs -*

LoginGraceTime 5s
MaxAuthTries 1
MaxSessions 2
MaxStartups 16

AuthenticationMethods publickey
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
PermitRootLogin no
PubkeyAuthentication yes
UsePAM yes

AllowAgentForwarding no
AllowStreamLocalForwarding no
AllowTcpForwarding no
GatewayPorts no
PermitListen none
PermitOpen none
PermitTunnel no
PermitUserEnvironment no
X11Forwarding no

AuthorizedKeysFile .ssh/authorized_keys
ClientAliveInterval 60
ClientAliveCountMax 2
TCPKeepAlive no
Compression no
